### ISSUE TITLE
Fail tests if template value unavailable

### ISSUE THREAD

**Issue by akajla09** [warrant-dev/apirunner#26]
When chaining test cases, it's possible for a test to fail and thus not generate a template value that is needed in a subsequent test. Right now, apirunner simply doesn't do a replacement in this case and still makes http requests.

Instead, it should simply fail the subsequent dependent tests since the template value is unavailable. This will improve the error logs and debugging.

**Comment by kkajla12** [comment]
I believe this was resolved in #28.
